---
abstract: 'Associate a Tapir handler with Dancer routes'
author:
  - 'Eric Waters <ewaters@gmail.com>'
build_requires:
  Test::Exception: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Tapir
provides:
  Dancer::LoggerMockObject:
    file: lib/Dancer/Plugin/Tapir.pm
    version: 0
  Dancer::Plugin::Tapir:
    file: lib/Dancer/Plugin/Tapir.pm
    version: 0.03
requires:
  Capture::Tiny: 0
  Dancer: 1.31
  JSON: 0
  Tapir: 0.02
resources:
  bugtracker: http://github.com/ewaters/dancer-plugin-tapir/issues?labels=bug
  license: http://dev.perl.org/licenses/
  repository: http://github.com/ewaters/dancer-plugin-tapir
version: 0.03
